services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    networks:
      - jewelry
    environment:
      - REACT_APP_API_URL=http://backend:5000

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - jewelry
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - jewelry

networks:
  jewelry:
    driver: bridge
